# Generated by Django 5.1.1 on 2024-10-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_conductor', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('licencia_conducir', models.CharField(max_length=20)),
                ('categoria_licencia', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('capacidad_ocupantes', models.IntegerField(blank=True, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionVehiculoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('hora_asignacion', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='taxista.conductor')),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='taxista.vehiculo')),
            ],
        ),
    ]
