# Generated by Django 5.1.1 on 2024-10-05 00:47

import taxista.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionvehiculoconductor',
            name='fecha_asignacion',
            field=models.DateField(validators=[taxista.validators.validar_fecha_asignacion]),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculoconductor',
            name='fecha_fin',
            field=models.DateField(validators=[taxista.validators.validar_fecha_fin]),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculoconductor',
            name='hora_asignacion',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculoconductor',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='apellido_materno',
            field=models.CharField(max_length=100, validators=[taxista.validators.validar_nombres_apellidos]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='apellido_paterno',
            field=models.CharField(max_length=100, validators=[taxista.validators.validar_nombres_apellidos]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='categoria_licencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=100, validators=[taxista.validators.validar_email]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_nacimiento',
            field=models.DateField(validators=[taxista.validators.validar_fecha_nacimiento]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(validators=[taxista.validators.validar_fecha_vencimiento_licencia]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombres',
            field=models.CharField(max_length=100, validators=[taxista.validators.validar_nombres_apellidos]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rut_conductor',
            field=models.CharField(max_length=12, unique=True, validators=[taxista.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(max_length=15, validators=[taxista.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_ocupantes',
            field=models.IntegerField(validators=[taxista.validators.validar_capacidad_ocupantes]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(max_length=50),
        ),
    ]
