# Generated by Django 5.1.1 on 2024-10-03 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_formacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut_colaborador', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('ano_titulacion', models.IntegerField(blank=True, null=True)),
                ('situacion_laboral', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('afp', models.ForeignKey(db_column='id_afp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.afp')),
                ('estado_civil', models.ForeignKey(db_column='id_estado_civil', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.estadocivil')),
                ('formacion', models.ForeignKey(db_column='id_formacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.formacion')),
                ('genero', models.ForeignKey(db_column='id_genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.genero')),
                ('prevision', models.ForeignKey(db_column='id_prevision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.prevision')),
                ('profesion', models.ForeignKey(db_column='id_profesion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.profesion')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('colaborador', models.ForeignKey(db_column='rut_colaborador', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('comuna', models.ForeignKey(db_column='id_comuna', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='colaboradores.region'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('sueldo_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sueldo_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_imponibles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('jornada_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.area')),
                ('cargo', models.ForeignKey(db_column='id_cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.cargo')),
                ('colaborador', models.ForeignKey(db_column='rut_colaborador', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_set', to='colaboradores.colaborador')),
                ('item_cargo', models.ForeignKey(db_column='id_item_cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.itemcargo')),
                ('tipo_contrato', models.ForeignKey(db_column='id_tipo_contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaboradores.tipocontrato')),
            ],
        ),
    ]
