# Generated by Django 5.1.1 on 2024-10-05 00:33

import colaboradores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_afp_alter_contrato_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='afp',
            field=models.CharField(choices=[('habitat', 'Habitat'), ('modelo', 'Modelo'), ('provida', 'Provida'), ('cuprum', 'Cuprum'), ('planvital', 'PlanVital'), ('sin_afp', 'Sin AFP')], default='sin_afp', max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='ano_titulacion',
            field=models.IntegerField(null=True, validators=[colaboradores.validators.validar_ano_titulacion]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='apellido_materno',
            field=models.CharField(max_length=100, validators=[colaboradores.validators.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='apellido_paterno',
            field=models.CharField(max_length=100, validators=[colaboradores.validators.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(validators=[colaboradores.validators.validar_fecha_nacimiento]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='formacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nombres',
            field=models.CharField(max_length=100, validators=[colaboradores.validators.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='prevision',
            field=models.CharField(choices=[('fonasa', 'FONASA'), ('isapre', 'ISAPRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rut_colaborador',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[colaboradores.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='situacion_laboral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono1',
            field=models.CharField(max_length=15, validators=[colaboradores.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono2',
            field=models.CharField(max_length=15, validators=[colaboradores.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_ingreso',
            field=models.DateField(validators=[colaboradores.validators.validar_fecha_ingreso]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='jornada_trabajo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='motivo_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='no_imponibles',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[colaboradores.validators.validar_sueldo]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='sueldo_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[colaboradores.validators.validar_sueldo]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='sueldo_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[colaboradores.validators.validar_sueldo]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='alias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
