# Generated by Django 5.1.1 on 2024-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_colaborador_afp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='afp',
            field=models.CharField(choices=[('habitat', 'Habitat'), ('modelo', 'Modelo'), ('provida', 'Provida'), ('cuprum', 'Cuprum'), ('planvital', 'PlanVital')], max_length=50),
        ),
    ]
