# Generated by Django 5.1.1 on 2024-10-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_alter_colaborador_afp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='situacion_laboral',
            field=models.CharField(blank=True, default='Activo', max_length=255),
        ),
    ]
