# Generated by Django 5.1.1 on 2024-10-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_alter_colaborador_situacion_laboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='afp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='prevision',
            field=models.CharField(max_length=50),
        ),
    ]
