# Generated by Django 5.1.1 on 2024-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0007_alter_colaborador_afp_alter_colaborador_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='turno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
