# Generated by Django 5.1.1 on 2024-10-16 17:43

import colaboradores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_contrato_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='rut_colaborador',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, validators=[colaboradores.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono1',
            field=models.CharField(max_length=20, validators=[colaboradores.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono2',
            field=models.CharField(max_length=20, validators=[colaboradores.validators.validar_telefono]),
        ),
    ]
