# Generated by Django 5.1.1 on 2024-10-16 17:49

import colaboradores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0009_alter_colaborador_rut_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='rut_colaborador',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[colaboradores.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono1',
            field=models.CharField(max_length=15, validators=[colaboradores.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono2',
            field=models.CharField(max_length=15, validators=[colaboradores.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='turno',
            field=models.CharField(blank=True, choices=[('7x7', 'Turno 7x7'), ('10x10', 'Turno 10x10'), ('4x4', 'Turno 4x4'), ('5x2', 'Turno 5x2'), ('N/A', 'Sin turno')], max_length=20, null=True),
        ),
    ]
