"""
Django settings for veteranminetrack project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv


CORS_ALLOW_ALL_ORIGINS = True

# Define BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent
# Archivos estáticos (CSS, JavaScript, imágenes)
STATIC_URL = "/static/"

# Añade esta línea
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Cargar las variables de entorno desde el archivo .env
load_dotenv()

# Acceder a las variables de entorno
API_AUTH_URL = os.getenv("API_AUTH_URL")
API_COLABORADORES_URL = os.getenv("API_COLABORADORES_URL")
API_TAXISTAS_URL = os.getenv("API_TAXISTAS_URL")
API_USERNAME = os.getenv("API_USERNAME")
API_PASSWORD = os.getenv("API_PASSWORD")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
AUTH_USER_MODEL = "usuarios.User"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-db5)#&xm7!+g!adz9*4z81q1j8=o9e*5)&u%11y1--%ew567_u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # otras apps
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_yasg",
    "usuarios",
    "viajes",
    "colaboradores",
    "taxista",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),  # Cambiado a 24 horas
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}

ROOT_URLCONF = "veteranminetrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "veteranminetrack.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.postgresql",
#        "NAME": "veteranminetrackbd",
#        "USER": "postgres",
#        "PASSWORD": "Wa1_t6podS%j",
#        "HOST": "veteranminetrack-bd.c2cluomtugij.us-east-1.rds.amazonaws.com",  # Por ejemplo, 'database-1.abcdefg.us-east-1.rds.amazonaws.com'
#        "PORT": "5432",
#    }
# }


DATABASES = {
    "default": dj_database_url.config(
        default="postgres://uebo7ladqar5lf:pe792d7a7d276526e627ae44dc089848242cd138f081eafde02be880bfacf6448@c9pv5s2sq0i76o.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dah6cmeb1d74qf",
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es"


USE_I18N = True


USE_TZ = True
TIME_ZONE = "America/Santiago"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
    "LOGIN_URL": "/admin/login/",  # Redirigir a la página de inicio de sesión de Django admin
    "LOGOUT_URL": "/admin/logout/",
    "USE_SESSION_AUTH": True,  # Hacer uso de la autenticación basada en sesión
}
