# Generated by Django 5.1.1 on 2024-10-12 15:58

import django.db.models.deletion
import viajes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxista', '0002_alter_asignacionvehiculoconductor_fecha_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=255)),
                ('descripcion_estado', models.TextField()),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ruta', models.CharField(max_length=255)),
                ('punto_inicial_latitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_latitud])),
                ('punto_inicial_longitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_longitud])),
                ('punto_final_latitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_latitud])),
                ('punto_final_longitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_longitud])),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_viaje', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField(validators=[viajes.validators.validar_fecha_salida])),
                ('hora_salida', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto_partida', models.CharField(max_length=255)),
                ('punto_destino', models.CharField(max_length=255)),
                ('numero_pasajeros', models.IntegerField(validators=[viajes.validators.validar_numero_pasajeros])),
                ('kilometros', models.DecimalField(decimal_places=2, max_digits=5, validators=[viajes.validators.validar_valor_no_negativo])),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10, validators=[viajes.validators.validar_valor_no_negativo])),
                ('estado_inicio_real', models.TimeField(blank=True, null=True)),
                ('estado_fin_real', models.TimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_viaje_anterior', models.BigIntegerField(blank=True, null=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[viajes.validators.validar_valor_no_negativo])),
                ('peajes', models.DecimalField(decimal_places=2, max_digits=10, validators=[viajes.validators.validar_valor_no_negativo])),
                ('tarifa_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[viajes.validators.validar_valor_no_negativo])),
                ('codigo_qr', models.CharField(max_length=255)),
                ('confirmado_por_conductor', models.BooleanField(default=False)),
                ('id_conductor', models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.ruta')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='taxista.vehiculo')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RutaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_latitud])),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=25, validators=[viajes.validators.validar_longitud])),
                ('orden', models.IntegerField(validators=[viajes.validators.validar_orden])),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_viaje', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_colaborador', models.CharField(max_length=255)),
                ('hora_asignacion', models.DateTimeField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.estado')),
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje')),
            ],
            options={
                'unique_together': {('rut_colaborador', 'id_viaje')},
            },
        ),
    ]
