# Generated by Django 5.1.1 on 2024-10-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecolaborador',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='viajes.estado'),
        ),
    ]
