# Generated by Django 5.1.1 on 2024-10-12 18:26

import django.db.models.deletion
import viajes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxista', '0002_alter_asignacionvehiculoconductor_fecha_asignacion_and_more'),
        ('viajes', '0003_alter_viaje_usuario_modificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_conductor',
            field=models.ForeignKey(blank=True, db_column='id_conductor', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxista.vehiculo'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='kilometros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[viajes.validators.validar_valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='numero_pasajeros',
            field=models.IntegerField(blank=True, null=True, validators=[viajes.validators.validar_numero_pasajeros]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='peajes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[viajes.validators.validar_valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='punto_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='punto_partida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tarifa_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[viajes.validators.validar_valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tarifa_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[viajes.validators.validar_valor_no_negativo]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[viajes.validators.validar_valor_no_negativo]),
        ),
    ]
